### ISSUE TITLE
enhead examples failing

### ISSUE THREAD

**Issue by callumwebb** [nacnudus/unpivotr#12]
Firstly, thanks for this package, I particularly appreciate the effort you've put in to the Spreadsheet Munging Strategies book!

I'm working on a spreadsheet similar to one of your examples with mixed levels of headers in the same column and ran into a problem with enhead. Here's the same issue on a simpler example where I can't reproduce your output.

```r
path <- system.file("extdata", "worked-examples.xlsx", package = "unpivotr")

all_cells <-
  xlsx_cells(path, sheets = "pivot-annotations") %>%
  dplyr::filter(col >= 4, !is_blank) %>% # Ignore the row headers in this example
  select(row, col, data_type, character, numeric) 

first_header_row <-
  dplyr::filter(all_cells, row == 2) %>%
  select(row, col, sex = character)

second_header_row <-
  dplyr::filter(all_cells, row == 3) %>%
  select(row, col, name = character)

data_cells <-
  dplyr::filter(all_cells, data_type == "numeric") %>%
  select(row, col, score = numeric)

enhead(data_cells, first_header_row, "NNW")
```

```
# Error in mutate_impl(.data, dots) : Evaluation error: argument "x" is missing, with no default.
```

It appears the simple "N" and "W" directions work, but I'm having an issue with NNW. I'll be able to a bit more investigating in a few days, let me know if I can assist.

**Comment by nacnudus** [comment]
Hi Callum, thanks for using the package :)

I can't reproduce the error.  Are you using the latest version?  `devtools::session_info()` will show you something like `unpivotr   * 0.3.1.9000 2018-06-08 Github (nacnudus/unpivotr@91cd0b9)`.

**Comment by callumwebb** [comment]
Just tested on my home PC and you're right, it succeeds as expected. 

I think the environment I was using had the latest version of the package installed but an older version of R. I'll share the session info when I'm back next week so that you have a record but I think you can close this.

More evidence that we need a more flexible policy at work!

**Comment by nacnudus** [comment]
Thanks for checking. I will push a stable update to CRAN eventually, which might help in constrained work environments.

**Comment by callumwebb** [comment]
For posterity, my session info (forgot I was also running 32-bit due to some Java dependency):

```
R version 3.3.3 (2017-03-06)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2      dplyr_0.7.4         tidyxl_1.0.1        unpivotr_0.3.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     tidyr_0.8.0      assertthat_0.2.0 digest_0.6.14    withr_2.1.2      R6_2.2.2         git2r_0.21.0     magrittr_1.5     pillar_1.2.3     httr_1.3.1      
[11] rlang_0.2.0      curl_3.2         devtools_1.13.5  tools_3.3.3      glue_1.2.0       purrr_0.2.4      pkgconfig_2.0.1  memoise_1.1.0    bindr_0.1.1      knitr_1.20      
[21] tibble_1.4.2  
```
