### ISSUE TITLE
Three-letter compass directions are really confusing

### ISSUE THREAD

**Issue by nacnudus** [nacnudus/unpivotr#23]

**Comment by bedantaguru** [comment]
I guess it's ok at least from readability perspective. 
`"NNW", "NNE", "ENE", "ESE", "SSE", "SSW", "WSW", "WNW"`.

Ideally, it may be written as:
`"N_NW","N_NE","E_NE","E_SE","S_SE","S_SW","W_SW","W_NW"`

As people can either read the first 1 or 2 letters and consider the last two or two. But above is definite segregation. 

However,  if anyone reads the first two letters then neither of the direction is commonly used direction:
`"NN","NN","EN","ES","SS","SS","WS","WN"`

And hence segregation is not required. 

But I guess you mean something else.

**Comment by nacnudus** [comment]
Thanks @bedantaguru yes I really mean that people find it hard to relate the direction to something in the spreadsheet.  I have decided to rename them to `up-left`, `up`, `left-up`, etc.  See the [branch](https://github.com/nacnudus/unpivotr/blob/upleft/man/direction.Rd).

**Comment by bedantaguru** [comment]
[Sorry to comment on the closed issue.]
Are you planning this for CRAN soon?
