### ISSUE TITLE
Failures with dev version of pillar

### ISSUE THREAD

**Issue by krlmlr** [nacnudus/unpivotr#24]
I'm seeing failures when checking {unpivotr} against the release candidate for {pillar}: https://github.com/r-lib/pillar/blob/master/revdep/problems.md#unpivotr. I think they are mostly related to subtle changes in what `type_sum()` returns. This now forwards to `vctrs::vec_abbr_ptype()` for most types, which will give more consistency in the long run.

Install the development version of {pillar} using :

```r
remotes::install_github("r-lib/pillar")
```

Read more about recent changes at https://github.com/r-lib/pillar/blob/master/NEWS.md.

I'll submit {pillar} to CRAN very soon because I've been asked to do it. If accepted, CRAN checks for your package will start failing. Sorry for the trouble.

Is there any chance that you can implement your tests in a way that's less dependent on what type_sum() returns?

**Comment by nacnudus** [comment]
Thanks for letting me know and investigating.  It's no trouble to me -- I owe so much to the tools you make.

**Comment by nacnudus** [comment]
Please may I include the defunct `pillar::type_sum()` [code](https://github.com/r-lib/pillar/blob/3a07902d79e86f3dbbacfc1b0ab9ce38968a961c/R/type-sum.R#L1-L53) in this package under the MIT license?  This would enable me to provide a fallback option to users for compatibility.  Otherwise the renaming of `fct -> fctr` and `cpl -> cplx` could break their code.

**Comment by krlmlr** [comment]
May I suggest that you implement your own generic that forwards to `type_sum()` and has methods only for the types that differ now? I believe it would be beneficial to eventually switch to tidyverse conventions.

I see that your package doesn't have known downstream dependencies on CRAN. Users who care about reproducible results can and should use a stable package library.

As for the code, it's not mine to give away I think. The first version seems to appear in tidyverse/tibble@95ced42.

**Comment by krlmlr** [comment]
Also, there will be a blog post, where we can describe the changes that affect {unpivotr} users.

**Comment by nacnudus** [comment]
I will switch to vctrs immediately, the `type_sum()` fallback is just to save users time.  Thanks for looking up the original tibble version.  I guess it isn't such a big deal, so I'll just let them know in NEWS and my own blog.

Bearing in mind that pillar *was* the tidyverse convention, and https://github.com/r-lib/pillar/issues/71 already changed `fctr -> fct` for consistency with rlang.  Now it's changing back.  Swings and roundabouts :)

**Comment by krlmlr** [comment]
Good point. Let's revisit -- perhaps it's a bit too early to switch to {vctrs}.

**Comment by krlmlr** [comment]
Thanks again. No action needed here.

Note that {vctrs} is still experimental -- `type_sum()` is likely the safer choice for now.
