### ISSUE TITLE
iterating behead on a list of row/column headers.

### ISSUE THREAD

**Issue by danstrobridge-Weston** [nacnudus/unpivotr#42]
Hi there.  I love unpivotr's elegance and use it all the time.  So much so, that I'm trying to write a wrapper function for my own package that will allow me to employ it on a broader spectrum of files with much less hard-coding in behead() statements.   Approximately half the data I work with match the format of your "groundwater data" structure in your munging strategies book and the other half is even easier to process.  Virtually all of my data conform to "up-left" and "left-up" conventions.  My goal is to simply supply as arguments to my wrapper function rowhdr and colhdr arguments that are essentially comma-separated strings of the order and name of the desired headers for each dimension that will be parsed via purrr's map function, do.call, or some other technique inside a dplyr chain.  Because I'm not particularly proficient with either of these tools, i'm having trouble getting them to work and am not certain if i'm simply calling them incorrectly or that the output of behead does not lend itself to iteration like I envision.  Regardless, I imagine that you probably have your own strategy for automated looping on headers and I'm curious if you might share a short example that I will emulate in my own code.  thanks so much.

**Comment by nacnudus** [comment]
Hi, thank you for your kind comments.

I don't use unpivotr much myself, so haven't developed any tools for iterating, but a while ago I wrote [some code](https://github.com/nacnudus/underground/tree/master/data-raw) that iterated through many similar tables in a single spreadsheet file.  Perhaps you can find some hints there, although it uses the old syntax for unpivotr, dplyr, tidyr, etc., so there are probably better ways now.

If you can share any code in a GitHub repo, I could try to offer some suggestions.

**Comment by nacnudus** [comment]
There is also [locatr](https://github.com/ianmoran11/locatr), which wraps unpivotr.
