### ISSUE TITLE
Merging cells does not update 'is_blank'

### ISSUE THREAD

**Issue by ammaraziz** [nacnudus/unpivotr#53]
Hi there,

Thanks for `unpivotr`, it's fantastic.

I'm merging several cells of which at least 1 will contain data ( characters). eg:

```
EX	          NA
Sich12048	Human sera
V1A.3/220M        NA
```
In this case `NA` represents empty cells.

When merging using `merge_rows` function, the cells are successfully merged and value is concatenated by the delimiter. Eg:
```
EX|Sich12048|V1A.3/220M 
NA|Human sera|NA
``` 
 However, the `is_blank` value should updated to reflect that the row now contains data. Before `is_blank` would contain a value for each cell eg `FALSE TRUE FALSE`, after `is_blank` contains 1 value which is always `FALSE`. This should be `TRUE` if the sum of `is_blank` is > 0.

Thanks,

Ammar

**Comment by ammaraziz** [comment]
The same issue for `data_type` as well. It is `blank`, which causes issues when `behead`ing the data.

**Comment by nacnudus** [comment]
Thanks @ammaraziz for your kind words.

I appreciate the annoyance in this case, but in general I think it's best to preserve the current logic, which is to preserve all the values of the first cell in each merge.  Here's one way to update them manually.

``` r
cells <- tibble::tribble(
  ~row, ~col,  ~data_type, ~is_blank,   ~character,
    1L,   1L, "character",     FALSE,         "EX",
    1L,   2L,          NA,        NA,           NA,
    2L,   1L, "character",     FALSE,  "Sich12048",
    2L,   2L, "character",     FALSE, "Human sera",
    3L,   1L, "character",     FALSE, "V1A.3/220M",
    3L,   2L,          NA,        NA,           NA
  )
cells
#> # A tibble: 6 × 5
#>     row   col data_type is_blank character 
#>   <int> <int> <chr>     <lgl>    <chr>     
#> 1     1     1 character FALSE    EX        
#> 2     1     2 <NA>      NA       <NA>      
#> 3     2     1 character FALSE    Sich12048 
#> 4     2     2 character FALSE    Human sera
#> 5     3     1 character FALSE    V1A.3/220M
#> 6     3     2 <NA>      NA       <NA>
unpivotr::rectify(cells)
#> # A tibble: 3 × 3
#>   `row/col` `1(A)`     `2(B)`    
#>       <int> <chr>      <chr>     
#> 1         1 EX         <NA>      
#> 2         2 Sich12048  Human sera
#> 3         3 V1A.3/220M <NA>
unpivotr::merge_rows(cells, 1:3, character, collapse = " | ")
#> # A tibble: 2 × 5
#>     col   row data_type is_blank character                  
#>   <int> <int> <chr>     <lgl>    <chr>                      
#> 1     1     1 character FALSE    EX | Sich12048 | V1A.3/220M
#> 2     2     1 <NA>      NA       NA | Human sera | NA

unpivotr::merge_rows(cells, 1:3, character, collapse = " | ") |>
  dplyr::mutate(
    is_blank = purrr::map_lgl(character, is.na),
    data_type = dplyr::if_else(
      !is_blank & !is.na(character),
      "character",
      data_type
    ),
  )
#> # A tibble: 2 × 5
#>     col   row data_type is_blank character                  
#>   <int> <int> <chr>     <lgl>    <chr>                      
#> 1     1     1 character FALSE    EX | Sich12048 | V1A.3/220M
#> 2     2     1 character FALSE    NA | Human sera | NA
```

<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Alternatively, the blank cells could be filtered out before the merge.  If your data came via tidyxl, look at the `include_blank_cells` option in `?xlsx_cells`.

**Comment by ammaraziz** [comment]
Hi @nacnudus I had figured this behavior was unintended thus the reason for this issue. If I may suggest something, can this behavior be documented somewhere so others do not get caught out like I did? 

Thanks for the advice regarding the how to filter blank cells. I will look into `include_blank_cells`. 

Feel free to close this issue as I think it's been resolved. 
Thanks again,

Ammar
