### ISSUE TITLE
suggestion: allow specification of column names in header joins

### ISSUE THREAD

**Issue by martinzuba** [nacnudus/unpivotr#6]
I love this package, and I would like to contribute a feature suggestion.

From the example:

```
# From each data cell, search for the nearest one of each of the headers
unpivoted <-
  datacells %>%
  NNW(col_headers$`1`) %>% # Search north (up) and north-west (up-left)
  N(col_headers$`2`) %>% # Search directly north (up)
  WNW(row_headers$`1`) %>% # Search west (left) and north-west
  W(row_headers$`2`) # Search directly left (west)
unpivoted
#> # A tibble: 72 x 7
#>      row   col chr   header.data header.header header.data.data  header.h…
#>    <int> <int> <chr> <chr>       <chr>         <chr>             <chr>    
#>  1     3     3 7000  Female      0 - 6         Bachelor's degree 15 - 24  
#>  2     4     3 12000 Female      0 - 6         Bachelor's degree 25 - 44  
#>  3     5     3 10000 Female      0 - 6         Bachelor's degree 45 - 64  
#>  4     7     3 29000 Female      0 - 6         Certificate       15 - 24  
#>  5     8     3 34000 Female      0 - 6         Certificate       25 - 44  
#>  6     9     3 30000 Female      0 - 6         Certificate       45 - 64  
#>  7    10     3 12000 Female      0 - 6         Certificate       65+      
#>  8    12     3 10000 Female      0 - 6         Diploma           25 - 44  
#>  9    13     3 6000  Female      0 - 6         Diploma           45 - 64  
#> 10    14     3 5000  Female      0 - 6         Diploma           65+      
#> # ... with 62 more rows
```

I would suggest specifying column names in this way:
```
NNW(col_headers$`1`, col_name = "sex") %>%
N(col_headers$`2`, col_name = "classification") %>%
WNW(row_headers$`1`, col_name = "degree") %>% 
W(row_headers$`2`, col_name = "age")
```

This would considerably facilitate obtaining better output.

**Comment by nacnudus** [comment]
Thank you 😊 

That's a neat suggestion.  Maybe the `NNW()` (etc.) functions could accept a `...` argument that is passed to `dplyr::rename()`, which would handle renaming multiple columns as well as all the `rlang` magic.  I'll think about it.

In the mean time I will rewrite the README not to use `split()`.  I've come to think that it's better to treat each row of headers individually, and assign the column names at that point.  So instead of

```r
row_headers <-
  cells %>%
  filter(col <= 2) %>%
  select(row, col, header = chr) %>%
  split(.$col)
```

I would now do the following

```r
qualification_headers <-
  cells %>%
  filter(col <= 2, row == 1) %>%
  select(row, col, qualification = chr)

age_headers <- 
  cells %>%
  filter(col <= 2, row == 2) %>%
  select(row, col, age = chr)
```

That way `NNW()` et al doesn't have to rename any headers because they're already unique, so they come out neatly.

**Comment by martinzuba** [comment]
Yes. `split()` may be a bad candidate since it produces lists with elements named `1`, `2`, etc.

Separate handling of header rows, and not using `split` is a good alternative if the number of headers is small. In my application, I have 6 header rows and 3 header columns (which is also why I am very grateful for unpivotr :-) )

It would probably be optimal if there was a function like split that takes a vector names of headers as argument and names the lists accordingly. Then, header join functions like `NWN()` … could assign these names as column names.

**Comment by nacnudus** [comment]
That sounds like a fine specimen.  Can you share it (or something like it)?

If all six rows of column headers aligned the same way, then perhaps `NNW()` coul take a single data frame of all the headers, and a vector of column names, and do the splitting and renaming internally.  `NNW()` would know to split by row, and `WNW()` would know to split by column.

**Comment by mkuhring** [comment]
Hey @nacnudus,

just stumbled over your package and like to express my appreciations as well. A package with this functionality seems kind of overdue for at least a decade now, one would think. So keep up the good work!

Regarding the column names, I was wondering whether this could actually automatized? I have data looking pretty similar to the output of the ftable() execution in the readme. I.e., I actually do have  specific values for header.data, header.header, header.data.data, header.header.header. So I was wondering whether the logic of ftable might be somehow reversible and adaptable for usage in unpivot to parse these fields as automatically as columns headers.

My data has two small additional differences though. I don't have an empty column below header.header. And I do have a column name for the target values (chr?) basically right on top of Female. However, I think this is rather inconsistent/unratable and I resp. my colleagues should probably make sure to correct for that manually.

**Comment by nacnudus** [comment]
Thanks for your kind words @mkuhring!

There's a lot of new work in the [api branch](https://github.com/nacnudus/unpivotr/tree/api), very roughly explained in the [vignette](https://github.com/nacnudus/unpivotr/blob/api/vignettes/worked-examples.Rmd) (you'll need to render it locally).  The pattern will be as follows.

```r
# Get some data from e.g. Excel
xlsx_cells(path) %>%
  # Interpret the first row as headers
  behead(NNW, `name-to-give-header-1`) %>%
  # Interpret the second row as headers
  behead(N, `name-to-give-header-2`) %>%
  # Interpret the first column as headers (etc. etc.)
  behead(W, `name-to-give-header-3`)
```

I don't know if you'll be able to get it to work yet -- by all means have a go and let me know how you get on.

**Comment by mkuhring** [comment]
Not sure if I understand your answer right. `name-to-give-header-1` is still a name I have to set in the code, right? It will no be automatically extracted from the excel sheet or will it? Unfortunately, I couldn't find this particular example in the new vignette.

**Comment by nacnudus** [comment]
Oh I see.  No, it won't automatically be extracted.

So far I have assumed that you know which header is which when you write the code.  Is that not the case for you?  I'd be interested to see/collect some examples, and then I can think about how to how to deal with them in a general way.

**Comment by mkuhring** [comment]
You are right. Usually the headers are known. Unfortunately, I can't provide you with examples of our data. But as I said, it basically looks the same like ftable puts the header in the upper left corner.

**Comment by nacnudus** [comment]
I'm closing this because the original issue is fixed in the latest version with `behead()`, and because without some examples I can't think about general solutions to the auto-column-naming problem.  Feel free to open a new issue for that if you can provide examples.

**Comment by mkuhring** [comment]
Sorry, totally forgot about the examples. The project where I used unpivot
is currently on hold, but it will be continuoued probably this winter. I
will check back with you then. Keep up the good work!

Duncan Garmonsway <notifications@github.com> schrieb am Do., 23. Aug. 2018,
16:34:
