### ISSUE TITLE
"Rectify" not found

### ISSUE THREAD

**Issue by JPennn** [nacnudus/unpivotr#9]
Issues using the rectify function. Everything is properly installed, but I keep getting 
Error in rectify(y) : could not find function "rectify"

The data I'm trying to clean is [Freedom House's Historical Democracy "Freedom Scores" by Country and Territory](https://freedomhouse.org/sites/default/files/Country%20and%20Territory%20Ratings%20and%20Statuses%20FIW1973-2018.xlsx).

Column headers are hierarchal, Year, sub-divided by columns for PR -Political Rights, CL - Civil Liberties, Freedom "Status" scores.  

(The years are not consistent over time and will need to be divided into start and end dates)

Thanks for looking into this!

**Comment by nacnudus** [comment]
Have you installed the GitHub version?  `rectify()` isn't in the CRAN version yet.
